### ISSUE TITLE
`redirectUri` is a required parameter but `embedded` mode recommends not setting it

### ISSUE THREAD

**Issue by xSAVIKx** [Finch-API/finch-api-java#256] opened 2024-07-22 21:23 UTC
I'm trying to proceed with the SDK and stuck upon the `redirectUri` usage. We're using embedded mode, so no redirect URI should be necessary, but I still have to set smth that is non-null while Kotlin has no support for nullable args.

What's the recommended way to work with embedded mode?

The [examples](https://github.com/Finch-API/finch-demo-nextjs/blob/main/pages/api/finch/callback.tsx#L18) specifically exclude redirect URI when using embedded mode.

**Comment by dgellow** [comment] 2024-07-23 14:58
Hi @xSAVIKx. Thanks for reporting this issue. `redirect_uri` should be optional according to the spec, if it is required in the current SDK that's indeed a bug. Could you tell us what version of the SDK you're currently using, and share more details regarding the error you're seeing?

Ideally a small example of your code + reported errors.

**Comment by xSAVIKx** [comment] 2024-07-23 15:56
This is actually related to https://github.com/Finch-API/finch-api-java/issues/257. Those are the errors

**Comment by dgellow** [comment] 2024-07-24 17:59
This issue is a duplicate of #257, the underlying cause is the same, and should be fixed by https://github.com/Finch-API/finch-api-java/pull/261.

**Closed** 2024-07-24 18:09 UTC
